services:
  api:
    restart: unless-stopped
    build:
      context: ./server
    ports:
      - "3004:8000"
    # volumes:
    #   - ./server:/app
    networks:
      - api-network

  web:
    restart: unless-stopped
    build:
      context: ./client
    environment:
      - REACT_APP_SUPABASE_URL
      - REACT_APP_SUPABASE_API
    env_file:
      - ./client/.env
    ports:
      - "3000:80"
    # volumes:
    #   - ./client:/app
    
    networks:
      - web-network
      - api-network
      - db-network
      - chat-network
  db:
    restart: unless-stopped
    build:
      context: ./db
    # environment:
    #   - 
    #   - 
    env_file:
      - ./db/.env
    ports:
      - "3003:80"
    # volumes:
    #   - ./chat:/app
    networks:
      - chat-network
      - api-network
  
  chat:
    restart: unless-stopped
    build:
      context: ./chat
    # environment:
    #   - 
    #   - 
    env_file:
      - ./chat/.env
    ports:
      - "3001:8501"
    # volumes:
    #   - ./db:/app
    networks:
      - db-network
      - api-network

networks:
  api-network:
    driver: bridge
  web-network:
    driver: bridge
  db-network:
    driver: bridge
  chat-network:
    driver: bridge