services:
  ai:
    restart: unless-stopped
    build:
      context: ./ai
    ports:
      - "8000:8000"
    # volumes:
    #   - ai:/app
    networks:
      - app-network

  web:
    restart: unless-stopped
    build:
      context: ./web
    ports:
      - "3001:3000"
    # volumes:
    #   - web:/app
    networks:
      - app-network

  dbconn:
    restart: unless-stopped
    build:
      context: ./dbconn
    ports:
      - "3002:3000"
    # volumes:
    #   - dbconn:/app
    networks:
      - app-network
  
  chat:
    restart: unless-stopped
    build:
      context: ./chat
    ports:
      - "5173:3000"
    # volumes:
    #   - chat:/app
    networks:
      - app-network
  
  redis:
    restart: unless-stopped
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge