services:
  ai:
    restart: unless-stopped
    build:
      context: ./ai
    ports:
      - "3004:8000"
    # volumes:
    #   - ai:/app
    networks:
      - ai-network
      - redis-network

  web:
    restart: unless-stopped
    build:
      context: ./web
    ports:
      - "3000:3000"
    # volumes:
    #   - web:/app
    networks:
      - web-network
      - ai-network
      - dbconn-network
      - chat-network

  dbconn:
    restart: unless-stopped
    build:
      context: ./dbconn
    ports:
      - "3003:80"
    # volumes:
    #   - dbconn:/app
    networks:
      - chat-network
      - ai-network
  
  chat:
    restart: unless-stopped
    build:
      context: ./chat
    ports:
      - "3001:8501"
    # volumes:
    #   - chat:/app
    networks:
      - dbconn-network
      - ai-network
      - redis-network
  
  redis:
    restart: unless-stopped
    build:
      context: ./redis
    ports:
      - "3005:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - redis-network
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "3002:3002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Path to nginx.conf
    depends_on:
      - web
      - chat
      - dbconn
      - ai
    networks:
      - web-network
      - ai-network
      - chat-network
      - dbconn-network
      - redis-network

networks:
  ai-network:
    driver: bridge
  web-network:
    driver: bridge
  dbconn-network:
    driver: bridge
  chat-network:
    driver: bridge
  redis-network:
    driver: bridge