services:
  api:
    restart: always
    build:
      context: ./server
    ports:
      - "8000:8000"
    # volumes:
    #   - ./server:/app
    networks:
      - api-network

  web:
    restart: always
    build:
      context: ./client
    environment:
      - REACT_APP_SUPABASE_URL
      - REACT_APP_SUPABASE_API
    env_file:
      - ./client/.env
    ports:
      - "80:80"
    # volumes:
    #   - ./client:/app
    
    networks:
      - web-network
      - api-network
      - db-network
  db:
    restart: always
    build:
      context: ./db
    # environment:
    #   - 
    #   - 
    env_file:
      - ./db/.env
    ports:
      - "5000:80"
    # volumes:
    #   - ./db:/app
    networks:
      - db-network
      - api-network

networks:
  api-network:
    driver: bridge
  web-network:
    driver: bridge
  db-network:
    driver: bridge