services:
  ai:
    restart: unless-stopped
    build:
      context: ai
    env_file: "ai/.env"
    ports:
      - "3004:8000"
    # volumes:
    #   - ai:/app
    networks:
      - ai-network

  web:
    restart: unless-stopped
    build:
      context: web
    env_file: web/.env
    ports:
      - "3000:80"
    # volumes:
    #   - web:/app
    networks:
      - web-network
      - ai-network
      - dbconn-network
      - chat-network

  dbconn:
    restart: unless-stopped
    build:
      context: dbconn
    env_file: dbconn/.env
    ports:
      - "3003:80"
    # volumes:
    #   - dbconn:/app
    networks:
      - chat-network
      - ai-network
  
  chat:
    restart: unless-stopped
    build:
      context: chat
    env_file: chat/.env
    ports:
      - "3001:8501"
    # volumes:
    #   - chat:/app
    networks:
      - dbconn-network
      - ai-network

networks:
  ai-network:
    driver: bridge
  web-network:
    driver: bridge
  dbconn-network:
    driver: bridge
  chat-network:
    driver: bridge