FROM redis:latest as build

# Copy a custom configuration file, if you have one
# ADD redis.conf /usr/local/etc/redis/redis.conf

# Use a custom entrypoint to start Redis with the custom configuration
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"